server:
  port: 9110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置

  application:
    name: apigateway # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务
      routes:
          # 配置的唯一标识，区别于其他 Route
        - id: service-edu
          # 路由指向的目的地 uri，即客户端请求最终被转发到的微服务
          # lb：使用负载均衡过滤器
          uri: lb://service-edu
          # 断言的作用是进行条件判断，只有断言都返回真，才会真正的执行路由
          predicates:
            # 路径形式的断言。当匹配这个路径时，断言条件成立
            - Path=/user/**, /*/edu/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**